- name:  create backend directory to copy the backend files
  file:
    path: ~/backend
    state: directory
     
- name: copy & unarchive backend directory
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name:  start the app
  become: yes
  shell:
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start