- name:  create backend directory to copy the backend files
  file:
    path: ~/backend
    state: directory
     
- name: copy & unarchive backend directory
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name:  start the app
  shell:
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

- name:  Install NOde Exporter
  shell:
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Configure a service
  template:
    src: "files/node-exporter.service"
    dest: "/etc/systemd/system/node-exporter.service"


- name: Configure systemd
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter
